### ISSUE TITLE
Differences between embl-api-validator-1.1.180 and the validator included in the submission pipeline

### ISSUE THREAD

**Issue by Juke34** [enasequence/sequencetools#24]
Apparently the way you check the consistency of the EMBL flat file into the submission pipeline is different from the one done by the embl-api-validator.

I have seen at least two cases that are worth it to be improved into the embl-api-validator to be similar to the behavior noticed into the submission pipeline:

1) I had a file where I was providing a wrong value for the “codon_start” optional qualifier for the CDS feature. The embl-api-validator-1.1.180 didn't see any error of the translated CDS, while the submission pipeline raised translational errors. I figured out the embl-api-validator-1.1.180 don't look at the provided value of the “codon_start” optional qualifier for the CDS feature and use the default value "1".
2) I had a file that passed the embl-api-validator-1.1.180 without error, but the submission pipeline raised the following error (12 times for 3', none in 5'):
` ERROR: Stop codon found at 3' partial end of the protein coding feature translation. Consider removing 3' partial location. line: 285738 of dekkera_genome.embl - dekkera_genome.embl`
Indeed I had wrong partial location represented by ">" or "<" for CDS feature where the CDS were actually complete.

It would be great that those 2 types of errors are detected upstream by the embl-api-validator instead of during the submission pipeline. It would save time and extra work for both, customer and ENA team.

Best regards

**Comment by raskoleinonen** [comment]
Apologies for this very late reply. Unlike at the time when this issue was created we now use exactly the same code to validate submissions before and after the submission event. Please note that the embl-api-validator is no longer supported as a stand alone tool but is incorporated into the Webin-CLI command line submission program that supports validation using the -validate option. 

More information about the Webin-CLI can be found from: 

https://ena-docs.readthedocs.io/en/latest/submit/general-guide/webin-cli.html
